sudo: required
services:
    - docker
script:
    - docker build -t packyzbq/log-pilot:systemd -f Dockerfile.fluentd .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWD
    - docker push packyzbq/log-pilot:systemd
